In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = TfidfVectorizer(analyzer='word', tokenizer=None, preprocessor=None, stop_words=None, smooth_idf=False)
count_vectorizer = CountVectorizer()




In [27]:
v = vectorizer.fit_transform(['hello','how', 'are', 'you'])
cv = count_vectorizer.fit(['hello','how', 'are', 'you'])

In [28]:
vectorizer.get_feature_names()


['are', 'hello', 'how', 'you']

In [29]:
count_vectorizer.get_feature_names()

['are', 'hello', 'how', 'you']

In [30]:
x = vectorizer.transform(['I am ok, how you are today my friend'])

In [31]:
print(x.toarray())

[[ 0.57735027  0.          0.57735027  0.57735027]]


In [32]:
v

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [12]:
cvx = count_vectorizer.transform(['I am ok, how are you'])

In [13]:
x.toarray()


array([[ 0.57735027,  0.        ,  0.57735027,  0.57735027]])

In [14]:
cvx.toarray()

array([[1, 0, 1, 1]])